version: 2
updates:

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: "12:45" # Update after the projects in the morning.
      timezone: "Europe/London"
