---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
# Vatu: PHP Stan
# Version: 1.0.0
# Author: Michael Bragg <mike@vatu.co.uk>

name: "PHPStan"

description: "Check the project against the PHPStan."

inputs:

  working-dir:
    description: "Path to PHPStan executable (optional)."
    required: false
    default: 'tools'

  test-command:
    description: "Composer script to run test (optional)."
    required: false
    default: 'test-phpstan'

runs:
  using: "composite"

  # Check the project against the local PHP Stan.
  #
  # Performs the following steps:
  # - Install tool.
  # - Logs debug information.
  # - Run test on project specific files.

  steps:

    - name: "Install tool."
      shell: bash
      run: composer update --working-dir=${{ inputs.working-dir }} --no-interaction --prefer-dist

    - name: "Logs debug information."
      shell: bash
      run: |
          php --version
          composer --version
          php ${{ inputs.working-dir }}/vendor/bin/phpstan --version

    - name: "Run test on project"
      shell: bash
      run: |
        composer run ${{ inputs.test-command }}
