# Vatu: Auto Approve Pull Request
# Description: Auto approve pull requests.
# Version: 1.0.0-alpha.1
# Author: Michael Bragg <mike@vatu.co.uk>
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "Auto Approve Pull Request"

on:
  workflow_call:

    inputs:

      runs-on:
        description: "Runner to be used by the parent workflow."
        required: false
        type: string
        default: ubuntu-latest

    secrets:
      BOT_ID:
        required: true
      BOT_KEY:
        required: true


jobs:

  # Auto Merge Pull Request.
  #
  # Performs the following steps:
  # - Generate Vatu Bot token
  # - Auto Approve Pull Request
  dependabot:

    name: "Dependabot Auto Merge PR."
    runs-on: ${{ inputs.runs-on }}

    steps:

      - name: "Generate Bot token."
        uses: tibdex/github-app-token@v1.7.0
        id: generate_token
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_KEY }}

      - name: "Debug"
        run: |
          echo ${{ toJSON(github) }}

      - name: "Auto Approve Pull Request."
        uses: actions/github-script@v6.3.3
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            github.rest.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
