# Vatu: Auto Merge Pull Requests
# Description: Auto merge pull requestst.
# Version: 1.0.0
# Author: Michael Bragg <mike@vatu.co.uk>
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "Auto Merge Pull Request"

on:
  workflow_call:

    inputs:

      runs-on:
        description: "Runner to be used by the parent workflow."
        required: false
        type: string
        default: ubuntu-latest

    secrets:
      BOT_ID:
        required: true
      BOT_KEY:
        required: true


jobs:

  # Auto Merge Pull Request.
  #
  # Performs the following steps:
  # - Generate Vatu Bot token
  # - Auto Approve Pull Request
  # - Auto Merges Pull Request
  # - Build notification message body
  # - Post Slack notification message
  dependabot:

    name: "Auto Merge Pull Request."
    runs-on: ${{ inputs.runs-on }}

    steps:

      - name: "Generate Bot token."
        uses: tibdex/github-app-token@v1.7.0
        id: generate_token
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_KEY }}

      - name: "Auto Approve Pull Request."
        uses: actions/github-script@v6.3.3
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            github.rest.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })

      - name: "Auto Merges Pull Request."
        uses: actions/github-script@v6.3.3
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            github.rest.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              merge_method: 'rebase'
            })

      - name: "Build notificaiton message body."
        run: echo "slack_message=$( printf '%s on %s repository.' "${{ github.head_ref || github.ref_name }}" "${ github.repository }" )" >> $GITHUB_ENV

      - name: "Post Slack notification message."
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'updates'
          slack-message: ${{ env.slack_message }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_DEPENDABOT_TOKEN }}
