# Vatu: Dependabot Auto Merge Pull Requests
# Description: Auto merge pull requests created by Dependabot.
# Version: 0.0.1-alpha
# Author: Michael Bragg <mike@vatu.co.uk>
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "Dependabot Auto Merge"

on:
  workflow_call:

    inputs:

      runs-on:
        description: "Runner to be used by the parent workflow."
        required: false
        type: string
        default: ubuntu-latest

jobs:

  # Dependabot Auto Merge.
  #
  # Performs the following steps:
  # - Generate Vatu Bot token
  # - Auto Approve Pull Request
  # - Auto Merges Pull Request
  # - Build notification message body
  # - Post Slack notification message
  dependabot:

    name: "Dependabot Auto Merge PR."
    runs-on: ${{ inputs.runs-on }}

    # Only run if the creator is Dependabot or previous workflow was successful.
    if: ${{ github.actor == 'dependabot[bot]' && github.event.workflow_run.conclusion == 'success' }}

    steps:

      - name: "Generate Vatu Bot token."
        uses: tibdex/github-app-token@v1.6
        id: generate_token
        with:
          app_id: ${{ secrets.VATU_BOT_ID }}
          private_key: ${{ secrets.VATU_BOT_KEY }}

      - name: "Auto Approve Pull Request."
        uses: actions/github-script@v6.1.0
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            github.rest.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.workflow_run.pull_requests[0].number,
              event: 'APPROVE'
            })

      - name: "Auto Merges Pull Request."
        uses: actions/github-script@v6.1.0
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            github.rest.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.workflow_run.pull_requests[0].number,
              merge_method: 'rebase'
            })

      - name: "Build notificaiton message body."
        run: echo "slack_message=$( printf '%s on %s repository.' "${{ github.event.workflow_run.head_branch }}" "${GITHUB_REPOSITORY}" )" >> $GITHUB_ENV

      - name: "Post Slack notification message."
        id: slack
        uses: slackapi/slack-github-action@v1.21
        with:
          channel-id: 'updates'
          slack-message: ${{ env.slack_message }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_DEPENDABOT_TOKEN }}
