# Vatu:   Dependabot Auto Merge PR
# Version 1.0.0
# Author: Michael Bragg <mike@vatu.co.uk>
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "Dependabot Auto Merge PR"

on:
  pull_request:
    branches:    
      - main

jobs:

  auto-merge:

    # Conditions for running workflow (project specific).
    if: >
      github.actor == 'dependabot[bot]'
    name: "Auto Merge PR"
    uses: vatu-team/workflows/.github/workflows/auto-merge-pr.yml@1.4.0
    with:
      runs-on: ubuntu-latest
    secrets:
      BOT_ID: ${{ secrets.VATU_BOT_ID }}
      BOT_KEY: ${{ secrets.VATU_BOT_KEY }}
