# Vatu: PHP CodeSniffer
# Version: 0.0.1-alpha
# Author: Michael Bragg <mike@vatu.co.uk>
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "PHP CodeSniffer"

on:
  workflow_call:

    inputs:
      version-php:
        required: false
        type: string
        default: "7.4"
      version-composer:
        required: false
        type: string
        default: "v2"

jobs:

  phpcs:

    name: "PHP CodeSniffer"
    runs-on: self-hosted

    steps:

      - name: "Checks out the repository."
        uses: "actions/checkout@v2"

      - name: "Debug."
        run: |
          echo '${{ github.event.inputs.version-php }}'
          echo '${{ github.event.inputs.version-composer }}'

      - name: "Sets up PHP with Composer."
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          coverage: "none"
          ini-values: "memory_limit=256M"
          tools: composer:v2
          ini-file: none
        env:
          COMPOSER_TOKEN: ${{ secrets.github-token }}

      - name: "Get Composer Cache Directory."
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: "Sets up Caching."
        uses: "actions/cache@v2"
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-composer-build-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-composer-build-

      - name: "Run PHP CodeSniffer Test."
        uses: "vatu-team/workflows/actions/php-codesniffer@action/phpcs"
