---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# Vatu:    PHP Parallel Lint
# Version: 1.1.0
# Author:  Michael Bragg <mike@vatu.co.uk>

name: "PHP Parallel Lint"

on:
  workflow_call:

    inputs:
      # Runner to be used by the parent workflow.
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      # PHP version used by the project.
      version-php:
        required: false
        type: string
        default: "7.4"
      # Composer version to be used by this workflow.
      version-composer:
        required: false
        type: string
        default: "v2"

env:
  COMPOSER_ALLOW_SUPERUSER: "1" # https://getcomposer.org/doc/03-cli.md#composer-allow-superuser

jobs:

  php-parallel-lint:

    name: "PHP Parallel Lint"
    runs-on: ${{ inputs.runs-on }}

    steps:

      - name: "Checks out the repository."
        uses: "actions/checkout@v4.1.2"

      - name: "Install PHP with Composer tool."
        uses: "shivammathur/setup-php@2.30.2"
        with:
          php-version: "${{ inputs.version-php }}"
          coverage: "none"
          ini-values: "memory_limit=-1"
          tools: cs2pr, composer:${{ inputs.version-composer }}
          ini-file: none
        env:
          COMPOSER_TOKEN: ${{ secrets.github-token }}

      - name: "Get Composer Cache Directory."
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Sets up Caching."
        uses: "actions/cache@v4.0.2"
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-composer-tools-${{ hashFiles('tools/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-composer-tools-

      - name: "Install dependencies."
        run: composer install --working-dir=tools --no-interaction --prefer-dist

      - name: "Run PHP Parallel Lint Test."
        run: composer run test-parallel-lint
